unstable_features = true
#error_on_line_overflow = true
#error_on_unformatted = true
fn_params_layout = "Vertical"
force_multiline_blocks = true
format_strings = true
imports_granularity = "Crate"
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
